pool:
    vmImage: 'ubuntu-16.04'

variables:
    buildConfiguration: 'Release'

steps:
    - script: dotnet publish --configuration $(buildConfiguration) -r win10-x64
      workingDirectory: '$(System.DefaultWorkingDirectory)/cli/gc-cli'
      displayName: 'Step 5 - Publish gc-cli'
      continueOnError: false

    - script: |
        echo $(System.DefaultWorkingDirectory)
      displayName: 'Step 6 - Run gc-cli'
      continueOnError: false