pool:
    vmImage: 'vs2017-win2016'

variables:
    buildConfiguration: 'Release'

steps:
- task: Npm@1
  displayName: 'Step 7 - Install npm package dependencies'
  inputs:
    command: install
    workingDir: WebClient
    verbose: false