pool:
    vmImage: 'vs2017-win2016'

variables:
    buildConfiguration: 'Release'

steps:
- script: npm install -g @angular/cli@7.2.2
  displayName: 'Step 7 - npm install @angular/cli 7.2.2'
  workingDirectory: '$(System.DefaultWorkingDirectory)\WebClient'

- script: npm install
  workingDirectory: '$(System.DefaultWorkingDirectory)\WebClient'
  displayName: 'Step 8 - npm install packages dependencies'

- script: ng build --prod
  workingDirectory: '$(System.DefaultWorkingDirectory)\WebClient'
  displayName: 'Step 9 - Build WebClient'

- task: ArchiveFiles@2
  displayName: 'Step 10 - Zip WebClient Artifacts'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)\WebClient\src\dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)\webclient.zip'