pool:
    vmImage: 'ubuntu-16.04'

variables:
    buildConfiguration: 'Release'

steps:
    - script: dotnet build --configuration $(buildConfiguration)
      workingDirectory: '$(System.DefaultWorkingDirectory)/cli/gc-cli'
      displayName: 'Build gc-cli'
      continueOnError: false

    - script: dotnet build --configuration $(buildConfiguration)
      workingDirectory: '$(System.DefaultWorkingDirectory)/WebApi/Blog.GrenitausConsulting.Core.Web.Api'
      displayName: 'Build Web API'
      continueOnError: false

    - script: dotnet test --configuration $(buildConfiguration)
      workingDirectory: '$(System.DefaultWorkingDirectory)/WebApi/Blog.GrenitausConsulting.Core.Unit.Tests'
      displayName: 'Run Web API Tests'
      continueOnError: false      

    - script: dotnet test --configuration $(buildConfiguration)
      workingDirectory: '$(System.DefaultWorkingDirectory)/cli/Blog.GrenitausConsulting.CLI.Core.Unit.Tests'
      displayName: 'Run gc-cli Tests'
      continueOnError: false            