pool:
    vmImage: 'ubuntu-16.04'

variables:
    buildConfiguration: 'Release'

steps:
    - script: dotnet publish --configuration $(buildConfiguration) -r win10-x64
      workingDirectory: '$(System.DefaultWorkingDirectory)/cli/gc-cli'
      displayName: 'Step 5 - Publish gc-cli'
      continueOnError: false

    - script: |
        echo $(System.DefaultWorkingDirectory) |
        SET @configdir=$(System.DefaultWorkingDirectory)\$(cli.argument.configdir) | 
        SET @outputdir=$(System.DefaultWorkingDirectory)\$(cli.argument.outputdir) |
        echo $(cli.argument.blogurl) |
        echo %@configdir% |
        echo %@outputdir% |
        gc-cli.exe -blogurl $(cli.argument.blogurl) -configdir %@configdir% -outputdir %@outputdir%
      workingDirectory: '$(System.DefaultWorkingDirectory)/cli/gc-cli'
      displayName: 'Step 5 - Publish gc-cli'
      continueOnError: false