pool:
    vmImage: 'ubuntu-16.04'

variables:
    buildConfiguration: 'Release'

steps:
    - script: dotnet publish --configuration $(buildConfiguration) -r win10-x64
      workingDirectory: '$(System.DefaultWorkingDirectory)/cli/gc-cli'
      displayName: 'Step 5 - Publish gc-cli'
      continueOnError: false

    - script: |
        '$(System.DefaultWorkingDirectory)/cli/gc-cli/bin/Release/netcoreapp2.0/win10-x64/publish/gc-cli.exe' -blogurl $(cli.argument.blogurl) \
        -configdir $(System.DefaultWorkingDirectory)/$(cli.argument.configdir) \
        -outputdir $(System.DefaultWorkingDirectory)/$(cli.argument.outputdir)
      displayName: 'Step 6 - Run gc-cli'
      continueOnError: false