pool:
    vmImage: 'vs2017-win2016'

variables:
    buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: '$(System.DefaultWorkingDirectory)\cli/gc-cli'
  displayName: 'Step 1 - Build gc-cli'
  continueOnError: false

- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: '$(System.DefaultWorkingDirectory)\WebApi\Blog.GrenitausConsulting.Core.Web.Api'
  displayName: 'Step 2 - Build Web API'
  continueOnError: false

- script: dotnet test --configuration $(buildConfiguration)
  workingDirectory: '$(System.DefaultWorkingDirectory)\WebApi\Blog.GrenitausConsulting.Core.Unit.Tests'
  displayName: 'Step 3 - Run Web API Tests'
  continueOnError: false

- script: dotnet test --configuration $(buildConfiguration)
  workingDirectory: '$(System.DefaultWorkingDirectory)\cli\Blog.GrenitausConsulting.CLI.Core.Unit.Tests'
  displayName: 'Step 4 - Run gc-cli Tests'
  continueOnError: false

- script: dotnet publish --configuration $(buildConfiguration) -r win10-x64
  workingDirectory: '$(System.DefaultWorkingDirectory)\cli\gc-cli'
  displayName: 'Step 5 - Publish gc-cli'
  continueOnError: false

- script: |
    SET @configdir=$(System.DefaultWorkingDirectory)\$(cli.argument.configdir)
    SET @outputdir=$(System.DefaultWorkingDirectory)\$(cli.argument.outputdir)

    gc-cli.exe -blogurl $(cli.argument.blogurl) -configdir %@configdir% -outputdir %@outputdir%
  workingDirectory: '$(System.DefaultWorkingDirectory)\cli\gc-cli\bin\Release\netcoreapp2.0\win10-x64\publish'
  displayName: 'Step 6 - Run gc-cli'
  continueOnError: false

- script: dotnet publish -c $(buildConfiguration) -o dist
  workingDirectory: '$(System.DefaultWorkingDirectory)\WebApi\Blog.GrenitausConsulting.Core.Web.Api'
  displayName: 'Step 7 - Publish Web API'
  continueOnError: false

- task: ArchiveFiles@2
  displayName: 'Step 8 - Zip WebApi Artifacts'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)\WebApi\Blog.GrenitausConsulting.Core.Web.Api\dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)\webapi.zip'  

- script: npm install -g @angular/cli@7.2.2
  displayName: 'Step 9 - npm install @angular/cli 7.2.2'
  workingDirectory: '$(System.DefaultWorkingDirectory)\WebClient'

- script: npm install
  workingDirectory: '$(System.DefaultWorkingDirectory)\WebClient'
  displayName: 'Step 10 - npm install packages dependencies'

- script: ng build --prod
  workingDirectory: '$(System.DefaultWorkingDirectory)\WebClient'
  displayName: 'Step 11 - Build WebClient'

- task: ArchiveFiles@2
  displayName: 'Step 12 - Zip WebClient Artifacts'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)\WebClient\dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)\webclient.zip'